manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/compressionKeyboards
  projects:
    - name: zmk
      remote: zmk
      revision: 3.5
      import: app/west.yml
  self:
    path: config
